# Generated by Django 4.1.5 on 2023-01-19 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='initial_depost',
            new_name='initial_deposit',
        ),
    ]
